// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NorthwindDataBase_MVC.Data;

#nullable disable

namespace NorthwindDataBase_MVC.Migrations.File
{
    [DbContext(typeof(FileContext))]
    [Migration("20230801125710_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");
#pragma warning restore 612, 618
        }
    }
}
